// Code generated by go-swagger; DO NOT EDIT.

package named_credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// NewCreateNamedCredentialParams creates a new CreateNamedCredentialParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateNamedCredentialParams() *CreateNamedCredentialParams {
	return &CreateNamedCredentialParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateNamedCredentialParamsWithTimeout creates a new CreateNamedCredentialParams object
// with the ability to set a timeout on a request.
func NewCreateNamedCredentialParamsWithTimeout(timeout time.Duration) *CreateNamedCredentialParams {
	return &CreateNamedCredentialParams{
		timeout: timeout,
	}
}

// NewCreateNamedCredentialParamsWithContext creates a new CreateNamedCredentialParams object
// with the ability to set a context for a request.
func NewCreateNamedCredentialParamsWithContext(ctx context.Context) *CreateNamedCredentialParams {
	return &CreateNamedCredentialParams{
		Context: ctx,
	}
}

// NewCreateNamedCredentialParamsWithHTTPClient creates a new CreateNamedCredentialParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateNamedCredentialParamsWithHTTPClient(client *http.Client) *CreateNamedCredentialParams {
	return &CreateNamedCredentialParams{
		HTTPClient: client,
	}
}

/*
CreateNamedCredentialParams contains all the parameters to send to the API endpoint

	for the create named credential operation.

	Typically these are written to a http.Request.
*/
type CreateNamedCredentialParams struct {

	// Body.
	Body *models.NamedCredential

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create named credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNamedCredentialParams) WithDefaults() *CreateNamedCredentialParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create named credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNamedCredentialParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create named credential params
func (o *CreateNamedCredentialParams) WithTimeout(timeout time.Duration) *CreateNamedCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create named credential params
func (o *CreateNamedCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create named credential params
func (o *CreateNamedCredentialParams) WithContext(ctx context.Context) *CreateNamedCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create named credential params
func (o *CreateNamedCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create named credential params
func (o *CreateNamedCredentialParams) WithHTTPClient(client *http.Client) *CreateNamedCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create named credential params
func (o *CreateNamedCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create named credential params
func (o *CreateNamedCredentialParams) WithBody(body *models.NamedCredential) *CreateNamedCredentialParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create named credential params
func (o *CreateNamedCredentialParams) SetBody(body *models.NamedCredential) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateNamedCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
