// Code generated by go-swagger; DO NOT EDIT.

package named_credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// CreateNamedCredentialReader is a Reader for the CreateNamedCredential structure.
type CreateNamedCredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNamedCredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateNamedCredentialCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateNamedCredentialDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateNamedCredentialCreated creates a CreateNamedCredentialCreated with default headers values
func NewCreateNamedCredentialCreated() *CreateNamedCredentialCreated {
	return &CreateNamedCredentialCreated{}
}

/*
CreateNamedCredentialCreated describes a response with status code 201, with default header values.

successful operation
*/
type CreateNamedCredentialCreated struct {
	Payload *models.NamedCredentialCreateResponse
}

func (o *CreateNamedCredentialCreated) Error() string {
	return fmt.Sprintf("[POST /NamedCredential][%d] createNamedCredentialCreated  %+v", 201, o.Payload)
}
func (o *CreateNamedCredentialCreated) GetPayload() *models.NamedCredentialCreateResponse {
	return o.Payload
}

func (o *CreateNamedCredentialCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NamedCredentialCreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNamedCredentialDefault creates a CreateNamedCredentialDefault with default headers values
func NewCreateNamedCredentialDefault(code int) *CreateNamedCredentialDefault {
	return &CreateNamedCredentialDefault{
		_statusCode: code,
	}
}

/*
CreateNamedCredentialDefault describes a response with status code -1, with default header values.

Error
*/
type CreateNamedCredentialDefault struct {
	_statusCode int

	Payload []*models.ErrorResponse
}

// Code gets the status code for the create named credential default response
func (o *CreateNamedCredentialDefault) Code() int {
	return o._statusCode
}

func (o *CreateNamedCredentialDefault) Error() string {
	return fmt.Sprintf("[POST /NamedCredential][%d] createNamedCredential default  %+v", o._statusCode, o.Payload)
}
func (o *CreateNamedCredentialDefault) GetPayload() []*models.ErrorResponse {
	return o.Payload
}

func (o *CreateNamedCredentialDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
