// Code generated by go-swagger; DO NOT EDIT.

package named_credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteNamedCredentialParams creates a new DeleteNamedCredentialParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteNamedCredentialParams() *DeleteNamedCredentialParams {
	return &DeleteNamedCredentialParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteNamedCredentialParamsWithTimeout creates a new DeleteNamedCredentialParams object
// with the ability to set a timeout on a request.
func NewDeleteNamedCredentialParamsWithTimeout(timeout time.Duration) *DeleteNamedCredentialParams {
	return &DeleteNamedCredentialParams{
		timeout: timeout,
	}
}

// NewDeleteNamedCredentialParamsWithContext creates a new DeleteNamedCredentialParams object
// with the ability to set a context for a request.
func NewDeleteNamedCredentialParamsWithContext(ctx context.Context) *DeleteNamedCredentialParams {
	return &DeleteNamedCredentialParams{
		Context: ctx,
	}
}

// NewDeleteNamedCredentialParamsWithHTTPClient creates a new DeleteNamedCredentialParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteNamedCredentialParamsWithHTTPClient(client *http.Client) *DeleteNamedCredentialParams {
	return &DeleteNamedCredentialParams{
		HTTPClient: client,
	}
}

/*
DeleteNamedCredentialParams contains all the parameters to send to the API endpoint

	for the delete named credential operation.

	Typically these are written to a http.Request.
*/
type DeleteNamedCredentialParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete named credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteNamedCredentialParams) WithDefaults() *DeleteNamedCredentialParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete named credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteNamedCredentialParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete named credential params
func (o *DeleteNamedCredentialParams) WithTimeout(timeout time.Duration) *DeleteNamedCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete named credential params
func (o *DeleteNamedCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete named credential params
func (o *DeleteNamedCredentialParams) WithContext(ctx context.Context) *DeleteNamedCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete named credential params
func (o *DeleteNamedCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete named credential params
func (o *DeleteNamedCredentialParams) WithHTTPClient(client *http.Client) *DeleteNamedCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete named credential params
func (o *DeleteNamedCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete named credential params
func (o *DeleteNamedCredentialParams) WithID(id string) *DeleteNamedCredentialParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete named credential params
func (o *DeleteNamedCredentialParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteNamedCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
