// Code generated by go-swagger; DO NOT EDIT.

package named_credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// NewUpdateNamedCredentialParams creates a new UpdateNamedCredentialParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateNamedCredentialParams() *UpdateNamedCredentialParams {
	return &UpdateNamedCredentialParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNamedCredentialParamsWithTimeout creates a new UpdateNamedCredentialParams object
// with the ability to set a timeout on a request.
func NewUpdateNamedCredentialParamsWithTimeout(timeout time.Duration) *UpdateNamedCredentialParams {
	return &UpdateNamedCredentialParams{
		timeout: timeout,
	}
}

// NewUpdateNamedCredentialParamsWithContext creates a new UpdateNamedCredentialParams object
// with the ability to set a context for a request.
func NewUpdateNamedCredentialParamsWithContext(ctx context.Context) *UpdateNamedCredentialParams {
	return &UpdateNamedCredentialParams{
		Context: ctx,
	}
}

// NewUpdateNamedCredentialParamsWithHTTPClient creates a new UpdateNamedCredentialParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateNamedCredentialParamsWithHTTPClient(client *http.Client) *UpdateNamedCredentialParams {
	return &UpdateNamedCredentialParams{
		HTTPClient: client,
	}
}

/*
UpdateNamedCredentialParams contains all the parameters to send to the API endpoint

	for the update named credential operation.

	Typically these are written to a http.Request.
*/
type UpdateNamedCredentialParams struct {

	// ID.
	ID string

	// Body.
	Body *models.NamedCredentialUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update named credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNamedCredentialParams) WithDefaults() *UpdateNamedCredentialParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update named credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNamedCredentialParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update named credential params
func (o *UpdateNamedCredentialParams) WithTimeout(timeout time.Duration) *UpdateNamedCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update named credential params
func (o *UpdateNamedCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update named credential params
func (o *UpdateNamedCredentialParams) WithContext(ctx context.Context) *UpdateNamedCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update named credential params
func (o *UpdateNamedCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update named credential params
func (o *UpdateNamedCredentialParams) WithHTTPClient(client *http.Client) *UpdateNamedCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update named credential params
func (o *UpdateNamedCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update named credential params
func (o *UpdateNamedCredentialParams) WithID(id string) *UpdateNamedCredentialParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update named credential params
func (o *UpdateNamedCredentialParams) SetID(id string) {
	o.ID = id
}

// WithBody adds the body to the update named credential params
func (o *UpdateNamedCredentialParams) WithBody(body *models.NamedCredentialUpdateRequest) *UpdateNamedCredentialParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update named credential params
func (o *UpdateNamedCredentialParams) SetBody(body *models.NamedCredentialUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNamedCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
