// Code generated by go-swagger; DO NOT EDIT.

package named_credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// UpdateNamedCredentialReader is a Reader for the UpdateNamedCredential structure.
type UpdateNamedCredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNamedCredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateNamedCredentialNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateNamedCredentialDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateNamedCredentialNoContent creates a UpdateNamedCredentialNoContent with default headers values
func NewUpdateNamedCredentialNoContent() *UpdateNamedCredentialNoContent {
	return &UpdateNamedCredentialNoContent{}
}

/*
UpdateNamedCredentialNoContent describes a response with status code 204, with default header values.

successful operation
*/
type UpdateNamedCredentialNoContent struct {
}

func (o *UpdateNamedCredentialNoContent) Error() string {
	return fmt.Sprintf("[PATCH /tooling/sobjects/NamedCredential/{Id}][%d] updateNamedCredentialNoContent ", 204)
}

func (o *UpdateNamedCredentialNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateNamedCredentialDefault creates a UpdateNamedCredentialDefault with default headers values
func NewUpdateNamedCredentialDefault(code int) *UpdateNamedCredentialDefault {
	return &UpdateNamedCredentialDefault{
		_statusCode: code,
	}
}

/*
UpdateNamedCredentialDefault describes a response with status code -1, with default header values.

Error
*/
type UpdateNamedCredentialDefault struct {
	_statusCode int

	Payload []*models.ErrorResponse
}

// Code gets the status code for the update named credential default response
func (o *UpdateNamedCredentialDefault) Code() int {
	return o._statusCode
}

func (o *UpdateNamedCredentialDefault) Error() string {
	return fmt.Sprintf("[PATCH /tooling/sobjects/NamedCredential/{Id}][%d] updateNamedCredential default  %+v", o._statusCode, o.Payload)
}
func (o *UpdateNamedCredentialDefault) GetPayload() []*models.ErrorResponse {
	return o.Payload
}

func (o *UpdateNamedCredentialDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
