// Code generated by go-swagger; DO NOT EDIT.

package event_relay_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// DeleteEventRelayConfigReader is a Reader for the DeleteEventRelayConfig structure.
type DeleteEventRelayConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteEventRelayConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteEventRelayConfigNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteEventRelayConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteEventRelayConfigNoContent creates a DeleteEventRelayConfigNoContent with default headers values
func NewDeleteEventRelayConfigNoContent() *DeleteEventRelayConfigNoContent {
	return &DeleteEventRelayConfigNoContent{}
}

/*
DeleteEventRelayConfigNoContent describes a response with status code 204, with default header values.

successful operation
*/
type DeleteEventRelayConfigNoContent struct {
}

func (o *DeleteEventRelayConfigNoContent) Error() string {
	return fmt.Sprintf("[DELETE /tooling/sobjects/EventRelayConfig/{Id}][%d] deleteEventRelayConfigNoContent ", 204)
}

func (o *DeleteEventRelayConfigNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteEventRelayConfigDefault creates a DeleteEventRelayConfigDefault with default headers values
func NewDeleteEventRelayConfigDefault(code int) *DeleteEventRelayConfigDefault {
	return &DeleteEventRelayConfigDefault{
		_statusCode: code,
	}
}

/*
DeleteEventRelayConfigDefault describes a response with status code -1, with default header values.

Error
*/
type DeleteEventRelayConfigDefault struct {
	_statusCode int

	Payload []*models.ErrorResponse
}

// Code gets the status code for the delete event relay config default response
func (o *DeleteEventRelayConfigDefault) Code() int {
	return o._statusCode
}

func (o *DeleteEventRelayConfigDefault) Error() string {
	return fmt.Sprintf("[DELETE /tooling/sobjects/EventRelayConfig/{Id}][%d] deleteEventRelayConfig default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteEventRelayConfigDefault) GetPayload() []*models.ErrorResponse {
	return o.Payload
}

func (o *DeleteEventRelayConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
