// Code generated by go-swagger; DO NOT EDIT.

package event_relay_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteEventRelayConfigParams creates a new DeleteEventRelayConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteEventRelayConfigParams() *DeleteEventRelayConfigParams {
	return &DeleteEventRelayConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEventRelayConfigParamsWithTimeout creates a new DeleteEventRelayConfigParams object
// with the ability to set a timeout on a request.
func NewDeleteEventRelayConfigParamsWithTimeout(timeout time.Duration) *DeleteEventRelayConfigParams {
	return &DeleteEventRelayConfigParams{
		timeout: timeout,
	}
}

// NewDeleteEventRelayConfigParamsWithContext creates a new DeleteEventRelayConfigParams object
// with the ability to set a context for a request.
func NewDeleteEventRelayConfigParamsWithContext(ctx context.Context) *DeleteEventRelayConfigParams {
	return &DeleteEventRelayConfigParams{
		Context: ctx,
	}
}

// NewDeleteEventRelayConfigParamsWithHTTPClient creates a new DeleteEventRelayConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteEventRelayConfigParamsWithHTTPClient(client *http.Client) *DeleteEventRelayConfigParams {
	return &DeleteEventRelayConfigParams{
		HTTPClient: client,
	}
}

/*
DeleteEventRelayConfigParams contains all the parameters to send to the API endpoint

	for the delete event relay config operation.

	Typically these are written to a http.Request.
*/
type DeleteEventRelayConfigParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete event relay config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEventRelayConfigParams) WithDefaults() *DeleteEventRelayConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete event relay config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEventRelayConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete event relay config params
func (o *DeleteEventRelayConfigParams) WithTimeout(timeout time.Duration) *DeleteEventRelayConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete event relay config params
func (o *DeleteEventRelayConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete event relay config params
func (o *DeleteEventRelayConfigParams) WithContext(ctx context.Context) *DeleteEventRelayConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete event relay config params
func (o *DeleteEventRelayConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete event relay config params
func (o *DeleteEventRelayConfigParams) WithHTTPClient(client *http.Client) *DeleteEventRelayConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete event relay config params
func (o *DeleteEventRelayConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete event relay config params
func (o *DeleteEventRelayConfigParams) WithID(id string) *DeleteEventRelayConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete event relay config params
func (o *DeleteEventRelayConfigParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEventRelayConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
