// Code generated by go-swagger; DO NOT EDIT.

package event_relay_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"log"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new event relay config API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for event relay config API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
CreateEventRelayConfig creates event relay config
*/
func (a *Client) CreateEventRelayConfig(params *CreateEventRelayConfigParams) (*CreateEventRelayConfigCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateEventRelayConfigParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createEventRelayConfig",
		Method:             "POST",
		PathPattern:        "/EventRelayConfig",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateEventRelayConfigReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		log.Printf("[TRACE] err: %+v", err)
		return nil, err
	}
	return result.(*CreateEventRelayConfigCreated), nil

}

/*
DeleteEventRelayConfig deletes event relay config
*/
func (a *Client) DeleteEventRelayConfig(params *DeleteEventRelayConfigParams) (*DeleteEventRelayConfigNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteEventRelayConfigParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteEventRelayConfig",
		Method:             "DELETE",
		PathPattern:        "/EventRelayConfig/{Id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteEventRelayConfigReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		log.Printf("[TRACE] err: %+v", err)
		return nil, err
	}
	return result.(*DeleteEventRelayConfigNoContent), nil

}

/*
GetEventRelayConfig gets event relay config
*/
func (a *Client) GetEventRelayConfig(params *GetEventRelayConfigParams) (*GetEventRelayConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetEventRelayConfigParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getEventRelayConfig",
		Method:             "GET",
		PathPattern:        "/EventRelayConfig/{Id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetEventRelayConfigReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		log.Printf("[TRACE] err: %+v", err)
		return nil, err
	}
	return result.(*GetEventRelayConfigOK), nil

}

/*
UpdateEventRelayConfig updates event relay config
*/
func (a *Client) UpdateEventRelayConfig(params *UpdateEventRelayConfigParams) (*UpdateEventRelayConfigNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateEventRelayConfigParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateEventRelayConfig",
		Method:             "PATCH",
		PathPattern:        "/EventRelayConfig/{Id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateEventRelayConfigReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		log.Printf("[TRACE] err: %+v", err)
		return nil, err
	}
	return result.(*UpdateEventRelayConfigNoContent), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
