// Code generated by go-swagger; DO NOT EDIT.

package event_relay_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEventRelayConfigParams creates a new GetEventRelayConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEventRelayConfigParams() *GetEventRelayConfigParams {
	return &GetEventRelayConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEventRelayConfigParamsWithTimeout creates a new GetEventRelayConfigParams object
// with the ability to set a timeout on a request.
func NewGetEventRelayConfigParamsWithTimeout(timeout time.Duration) *GetEventRelayConfigParams {
	return &GetEventRelayConfigParams{
		timeout: timeout,
	}
}

// NewGetEventRelayConfigParamsWithContext creates a new GetEventRelayConfigParams object
// with the ability to set a context for a request.
func NewGetEventRelayConfigParamsWithContext(ctx context.Context) *GetEventRelayConfigParams {
	return &GetEventRelayConfigParams{
		Context: ctx,
	}
}

// NewGetEventRelayConfigParamsWithHTTPClient creates a new GetEventRelayConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEventRelayConfigParamsWithHTTPClient(client *http.Client) *GetEventRelayConfigParams {
	return &GetEventRelayConfigParams{
		HTTPClient: client,
	}
}

/*
GetEventRelayConfigParams contains all the parameters to send to the API endpoint

	for the get event relay config operation.

	Typically these are written to a http.Request.
*/
type GetEventRelayConfigParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get event relay config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEventRelayConfigParams) WithDefaults() *GetEventRelayConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get event relay config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEventRelayConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get event relay config params
func (o *GetEventRelayConfigParams) WithTimeout(timeout time.Duration) *GetEventRelayConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get event relay config params
func (o *GetEventRelayConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get event relay config params
func (o *GetEventRelayConfigParams) WithContext(ctx context.Context) *GetEventRelayConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get event relay config params
func (o *GetEventRelayConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get event relay config params
func (o *GetEventRelayConfigParams) WithHTTPClient(client *http.Client) *GetEventRelayConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get event relay config params
func (o *GetEventRelayConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get event relay config params
func (o *GetEventRelayConfigParams) WithID(id string) *GetEventRelayConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get event relay config params
func (o *GetEventRelayConfigParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventRelayConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
