// Code generated by go-swagger; DO NOT EDIT.

package event_relay_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// NewUpdateEventRelayConfigParams creates a new UpdateEventRelayConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateEventRelayConfigParams() *UpdateEventRelayConfigParams {
	return &UpdateEventRelayConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateEventRelayConfigParamsWithTimeout creates a new UpdateEventRelayConfigParams object
// with the ability to set a timeout on a request.
func NewUpdateEventRelayConfigParamsWithTimeout(timeout time.Duration) *UpdateEventRelayConfigParams {
	return &UpdateEventRelayConfigParams{
		timeout: timeout,
	}
}

// NewUpdateEventRelayConfigParamsWithContext creates a new UpdateEventRelayConfigParams object
// with the ability to set a context for a request.
func NewUpdateEventRelayConfigParamsWithContext(ctx context.Context) *UpdateEventRelayConfigParams {
	return &UpdateEventRelayConfigParams{
		Context: ctx,
	}
}

// NewUpdateEventRelayConfigParamsWithHTTPClient creates a new UpdateEventRelayConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateEventRelayConfigParamsWithHTTPClient(client *http.Client) *UpdateEventRelayConfigParams {
	return &UpdateEventRelayConfigParams{
		HTTPClient: client,
	}
}

/*
UpdateEventRelayConfigParams contains all the parameters to send to the API endpoint

	for the update event relay config operation.

	Typically these are written to a http.Request.
*/
type UpdateEventRelayConfigParams struct {

	// ID.
	ID string

	// Body.
	Body *models.EventRelayConfigUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update event relay config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEventRelayConfigParams) WithDefaults() *UpdateEventRelayConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update event relay config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEventRelayConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update event relay config params
func (o *UpdateEventRelayConfigParams) WithTimeout(timeout time.Duration) *UpdateEventRelayConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update event relay config params
func (o *UpdateEventRelayConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update event relay config params
func (o *UpdateEventRelayConfigParams) WithContext(ctx context.Context) *UpdateEventRelayConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update event relay config params
func (o *UpdateEventRelayConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update event relay config params
func (o *UpdateEventRelayConfigParams) WithHTTPClient(client *http.Client) *UpdateEventRelayConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update event relay config params
func (o *UpdateEventRelayConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update event relay config params
func (o *UpdateEventRelayConfigParams) WithID(id string) *UpdateEventRelayConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update event relay config params
func (o *UpdateEventRelayConfigParams) SetID(id string) {
	o.ID = id
}

// WithBody adds the body to the update event relay config params
func (o *UpdateEventRelayConfigParams) WithBody(body *models.EventRelayConfigUpdateRequest) *UpdateEventRelayConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update event relay config params
func (o *UpdateEventRelayConfigParams) SetBody(body *models.EventRelayConfigUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateEventRelayConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
