// Code generated by go-swagger; DO NOT EDIT.

package event_relay_feedback

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEventRelayFeedbackParams creates a new GetEventRelayFeedbackParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEventRelayFeedbackParams() *GetEventRelayFeedbackParams {
	return &GetEventRelayFeedbackParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEventRelayFeedbackParamsWithTimeout creates a new GetEventRelayFeedbackParams object
// with the ability to set a timeout on a request.
func NewGetEventRelayFeedbackParamsWithTimeout(timeout time.Duration) *GetEventRelayFeedbackParams {
	return &GetEventRelayFeedbackParams{
		timeout: timeout,
	}
}

// NewGetEventRelayFeedbackParamsWithContext creates a new GetEventRelayFeedbackParams object
// with the ability to set a context for a request.
func NewGetEventRelayFeedbackParamsWithContext(ctx context.Context) *GetEventRelayFeedbackParams {
	return &GetEventRelayFeedbackParams{
		Context: ctx,
	}
}

// NewGetEventRelayFeedbackParamsWithHTTPClient creates a new GetEventRelayFeedbackParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEventRelayFeedbackParamsWithHTTPClient(client *http.Client) *GetEventRelayFeedbackParams {
	return &GetEventRelayFeedbackParams{
		HTTPClient: client,
	}
}

/*
GetEventRelayFeedbackParams contains all the parameters to send to the API endpoint

	for the get event relay feedback operation.

	Typically these are written to a http.Request.
*/
type GetEventRelayFeedbackParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get event relay feedback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEventRelayFeedbackParams) WithDefaults() *GetEventRelayFeedbackParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get event relay feedback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEventRelayFeedbackParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get event relay feedback params
func (o *GetEventRelayFeedbackParams) WithTimeout(timeout time.Duration) *GetEventRelayFeedbackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get event relay feedback params
func (o *GetEventRelayFeedbackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get event relay feedback params
func (o *GetEventRelayFeedbackParams) WithContext(ctx context.Context) *GetEventRelayFeedbackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get event relay feedback params
func (o *GetEventRelayFeedbackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get event relay feedback params
func (o *GetEventRelayFeedbackParams) WithHTTPClient(client *http.Client) *GetEventRelayFeedbackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get event relay feedback params
func (o *GetEventRelayFeedbackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get event relay feedback params
func (o *GetEventRelayFeedbackParams) WithID(id string) *GetEventRelayFeedbackParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get event relay feedback params
func (o *GetEventRelayFeedbackParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventRelayFeedbackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
