// Code generated by go-swagger; DO NOT EDIT.

package platform_event_channel_member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// CreatePlatformEventChannelMemberReader is a Reader for the CreatePlatformEventChannelMember structure.
type CreatePlatformEventChannelMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePlatformEventChannelMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreatePlatformEventChannelMemberCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreatePlatformEventChannelMemberDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreatePlatformEventChannelMemberCreated creates a CreatePlatformEventChannelMemberCreated with default headers values
func NewCreatePlatformEventChannelMemberCreated() *CreatePlatformEventChannelMemberCreated {
	return &CreatePlatformEventChannelMemberCreated{}
}

/*
CreatePlatformEventChannelMemberCreated describes a response with status code 201, with default header values.

successful operation
*/
type CreatePlatformEventChannelMemberCreated struct {
	Payload *models.PlatformEventChannelMemberCreateResponse
}

func (o *CreatePlatformEventChannelMemberCreated) Error() string {
	return fmt.Sprintf("[POST /tooling/sobjects/PlatformEventChannelMember][%d] createPlatformEventChannelMemberCreated  %+v", 201, o.Payload)
}
func (o *CreatePlatformEventChannelMemberCreated) GetPayload() *models.PlatformEventChannelMemberCreateResponse {
	return o.Payload
}

func (o *CreatePlatformEventChannelMemberCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PlatformEventChannelMemberCreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePlatformEventChannelMemberDefault creates a CreatePlatformEventChannelMemberDefault with default headers values
func NewCreatePlatformEventChannelMemberDefault(code int) *CreatePlatformEventChannelMemberDefault {
	return &CreatePlatformEventChannelMemberDefault{
		_statusCode: code,
	}
}

/*
CreatePlatformEventChannelMemberDefault describes a response with status code -1, with default header values.

Error
*/
type CreatePlatformEventChannelMemberDefault struct {
	_statusCode int

	Payload []*models.ErrorResponse
}

// Code gets the status code for the create platform event channel member default response
func (o *CreatePlatformEventChannelMemberDefault) Code() int {
	return o._statusCode
}

func (o *CreatePlatformEventChannelMemberDefault) Error() string {
	return fmt.Sprintf("[POST /tooling/sobjects/PlatformEventChannelMember][%d] createPlatformEventChannelMember default  %+v", o._statusCode, o.Payload)
}
func (o *CreatePlatformEventChannelMemberDefault) GetPayload() []*models.ErrorResponse {
	return o.Payload
}

func (o *CreatePlatformEventChannelMemberDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
