// Code generated by go-swagger; DO NOT EDIT.

package platform_event_channel_member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeletePlatformEventChannelMemberParams creates a new DeletePlatformEventChannelMemberParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeletePlatformEventChannelMemberParams() *DeletePlatformEventChannelMemberParams {
	return &DeletePlatformEventChannelMemberParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePlatformEventChannelMemberParamsWithTimeout creates a new DeletePlatformEventChannelMemberParams object
// with the ability to set a timeout on a request.
func NewDeletePlatformEventChannelMemberParamsWithTimeout(timeout time.Duration) *DeletePlatformEventChannelMemberParams {
	return &DeletePlatformEventChannelMemberParams{
		timeout: timeout,
	}
}

// NewDeletePlatformEventChannelMemberParamsWithContext creates a new DeletePlatformEventChannelMemberParams object
// with the ability to set a context for a request.
func NewDeletePlatformEventChannelMemberParamsWithContext(ctx context.Context) *DeletePlatformEventChannelMemberParams {
	return &DeletePlatformEventChannelMemberParams{
		Context: ctx,
	}
}

// NewDeletePlatformEventChannelMemberParamsWithHTTPClient creates a new DeletePlatformEventChannelMemberParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeletePlatformEventChannelMemberParamsWithHTTPClient(client *http.Client) *DeletePlatformEventChannelMemberParams {
	return &DeletePlatformEventChannelMemberParams{
		HTTPClient: client,
	}
}

/*
DeletePlatformEventChannelMemberParams contains all the parameters to send to the API endpoint

	for the delete platform event channel member operation.

	Typically these are written to a http.Request.
*/
type DeletePlatformEventChannelMemberParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete platform event channel member params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePlatformEventChannelMemberParams) WithDefaults() *DeletePlatformEventChannelMemberParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete platform event channel member params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePlatformEventChannelMemberParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete platform event channel member params
func (o *DeletePlatformEventChannelMemberParams) WithTimeout(timeout time.Duration) *DeletePlatformEventChannelMemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete platform event channel member params
func (o *DeletePlatformEventChannelMemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete platform event channel member params
func (o *DeletePlatformEventChannelMemberParams) WithContext(ctx context.Context) *DeletePlatformEventChannelMemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete platform event channel member params
func (o *DeletePlatformEventChannelMemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete platform event channel member params
func (o *DeletePlatformEventChannelMemberParams) WithHTTPClient(client *http.Client) *DeletePlatformEventChannelMemberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete platform event channel member params
func (o *DeletePlatformEventChannelMemberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete platform event channel member params
func (o *DeletePlatformEventChannelMemberParams) WithID(id string) *DeletePlatformEventChannelMemberParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete platform event channel member params
func (o *DeletePlatformEventChannelMemberParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePlatformEventChannelMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
