// Code generated by go-swagger; DO NOT EDIT.

package platform_event_channel_member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// NewUpdatePlatformEventChannelMemberParams creates a new UpdatePlatformEventChannelMemberParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePlatformEventChannelMemberParams() *UpdatePlatformEventChannelMemberParams {
	return &UpdatePlatformEventChannelMemberParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePlatformEventChannelMemberParamsWithTimeout creates a new UpdatePlatformEventChannelMemberParams object
// with the ability to set a timeout on a request.
func NewUpdatePlatformEventChannelMemberParamsWithTimeout(timeout time.Duration) *UpdatePlatformEventChannelMemberParams {
	return &UpdatePlatformEventChannelMemberParams{
		timeout: timeout,
	}
}

// NewUpdatePlatformEventChannelMemberParamsWithContext creates a new UpdatePlatformEventChannelMemberParams object
// with the ability to set a context for a request.
func NewUpdatePlatformEventChannelMemberParamsWithContext(ctx context.Context) *UpdatePlatformEventChannelMemberParams {
	return &UpdatePlatformEventChannelMemberParams{
		Context: ctx,
	}
}

// NewUpdatePlatformEventChannelMemberParamsWithHTTPClient creates a new UpdatePlatformEventChannelMemberParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePlatformEventChannelMemberParamsWithHTTPClient(client *http.Client) *UpdatePlatformEventChannelMemberParams {
	return &UpdatePlatformEventChannelMemberParams{
		HTTPClient: client,
	}
}

/*
UpdatePlatformEventChannelMemberParams contains all the parameters to send to the API endpoint

	for the update platform event channel member operation.

	Typically these are written to a http.Request.
*/
type UpdatePlatformEventChannelMemberParams struct {

	// ID.
	ID string

	// Body.
	Body *models.PlatformEventChannelMemberUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update platform event channel member params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePlatformEventChannelMemberParams) WithDefaults() *UpdatePlatformEventChannelMemberParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update platform event channel member params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePlatformEventChannelMemberParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) WithTimeout(timeout time.Duration) *UpdatePlatformEventChannelMemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) WithContext(ctx context.Context) *UpdatePlatformEventChannelMemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) WithHTTPClient(client *http.Client) *UpdatePlatformEventChannelMemberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) WithID(id string) *UpdatePlatformEventChannelMemberParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) SetID(id string) {
	o.ID = id
}

// WithBody adds the body to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) WithBody(body *models.PlatformEventChannelMemberUpdateRequest) *UpdatePlatformEventChannelMemberParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update platform event channel member params
func (o *UpdatePlatformEventChannelMemberParams) SetBody(body *models.PlatformEventChannelMemberUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePlatformEventChannelMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
