//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"log"
	"vestahealthcare/client"
	"vestahealthcare/client/event_relay_config"
	"vestahealthcare/salesforce/schemata"
	"vestahealthcare/salesforce/utils"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

/*
EventRelayConfig event relay config API
*/

func EventRelayConfig() *schema.Resource {
	return &schema.Resource{
		CreateContext: createEventRelayConfig,
		DeleteContext: deleteEventRelayConfig,
		ReadContext:   getEventRelayConfig,
		UpdateContext: updateEventRelayConfig,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: schemata.EventRelayConfigSchema(),
	}
}

func DataResourceEventRelayConfig() *schema.Resource {
	return &schema.Resource{
		Schema: schemata.DataSourceEventRelayConfigSchema(),
	}
}

func createEventRelayConfig(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	model := schemata.EventRelayConfigModel(d)
	params := event_relay_config.NewCreateEventRelayConfigParams()
	params.SetBody(model)

	client := m.(*client.SalesforceRESTAPI)

	resp, err := client.EventRelayConfig.CreateEventRelayConfig(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	schemata.SetEventRelayConfigCreateResponseResourceData(d, respModel)
	return diags
}

func deleteEventRelayConfig(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	params := event_relay_config.NewDeleteEventRelayConfigParams()

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		params.ID = idVal.(string)
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - Id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	client := m.(*client.SalesforceRESTAPI)

	resp, err := client.EventRelayConfig.DeleteEventRelayConfig(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	d.SetId("")
	return diags
}

func getEventRelayConfig(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	params := event_relay_config.NewGetEventRelayConfigParams()

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		params.ID = idVal.(string)
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - Id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	client := m.(*client.SalesforceRESTAPI)

	resp, err := client.EventRelayConfig.GetEventRelayConfig(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	schemata.SetEventRelayConfigResourceData(d, respModel)

	return diags
}

func updateEventRelayConfig(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	d.Partial(true)

	model := schemata.EventRelayConfigUpdateRequestModel(d)
	params := event_relay_config.NewUpdateEventRelayConfigParams()

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		params.ID = idVal.(string)
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - Id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	params.SetBody(model)

	// list of available properties
	props := schemata.GetEventRelayConfigPropertyFields()

	// loops through array of properties to see which one has changed, the ones that did not change are removed from the list
	for _, v := range props {
		if d.HasChange(v) {
		} else {
			props = utils.Remove(props, v)
		}
	}

	client := m.(*client.SalesforceRESTAPI)

	// makes a bulk update for all properties that were changed
	resp, err := client.EventRelayConfig.UpdateEventRelayConfig(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}
	d.Partial(false)

	return diags
}
