//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"log"
	"vestahealthcare/client"
	"vestahealthcare/client/event_relay_feedback"
	"vestahealthcare/salesforce/schemata"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

/*
EventRelayFeedback event relay feedback API
*/

func DataResourceEventRelayFeedback() *schema.Resource {
	return &schema.Resource{
		ReadContext: getEventRelayFeedback,
		Schema:      schemata.DataSourceEventRelayFeedbackSchema(),
	}
}

func getEventRelayFeedback(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	params := event_relay_feedback.NewGetEventRelayFeedbackParams()

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		params.ID = idVal.(string)
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - Id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	client := m.(*client.SalesforceRESTAPI)

	resp, err := client.EventRelayFeedback.GetEventRelayFeedback(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	schemata.SetEventRelayFeedbackResourceData(d, respModel)

	return diags
}
