//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"log"
	"vestahealthcare/client"
	"vestahealthcare/client/named_credential"
	"vestahealthcare/salesforce/schemata"
	"vestahealthcare/salesforce/utils"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

/*
NamedCredential named credential API
*/

func NamedCredential() *schema.Resource {
	return &schema.Resource{
		CreateContext: createNamedCredential,
		DeleteContext: deleteNamedCredential,
		ReadContext:   getNamedCredential,
		UpdateContext: updateNamedCredential,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: schemata.NamedCredentialSchema(),
	}
}

func DataResourceNamedCredential() *schema.Resource {
	return &schema.Resource{
		ReadContext: getNamedCredential,
		Schema:      schemata.DataSourceNamedCredentialSchema(),
	}
}

func createNamedCredential(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	model := schemata.NamedCredentialModel(d)
	params := named_credential.NewCreateNamedCredentialParams()
	params.SetBody(model)

	client := m.(*client.SalesforceRESTAPI)

	resp, err := client.NamedCredential.CreateNamedCredential(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	schemata.SetNamedCredentialCreateResponseResourceData(d, respModel)
	return diags
}

func deleteNamedCredential(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	params := named_credential.NewDeleteNamedCredentialParams()

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		params.ID = idVal.(string)
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - Id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	client := m.(*client.SalesforceRESTAPI)

	resp, err := client.NamedCredential.DeleteNamedCredential(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	d.SetId("")
	return diags
}

func getNamedCredential(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	params := named_credential.NewGetNamedCredentialParams()

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		params.ID = idVal.(string)
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - Id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	client := m.(*client.SalesforceRESTAPI)

	resp, err := client.NamedCredential.GetNamedCredential(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	schemata.SetNamedCredentialResourceData(d, respModel)

	return diags
}

func updateNamedCredential(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	d.Partial(true)

	model := schemata.NamedCredentialUpdateRequestModel(d)
	params := named_credential.NewUpdateNamedCredentialParams()

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		params.ID = idVal.(string)
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - Id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	params.SetBody(model)

	// list of available properties
	props := schemata.GetNamedCredentialPropertyFields()

	// loops through array of properties to see which one has changed, the ones that did not change are removed from the list
	for _, v := range props {
		if d.HasChange(v) {
		} else {
			props = utils.Remove(props, v)
		}
	}

	client := m.(*client.SalesforceRESTAPI)

	// makes a bulk update for all properties that were changed
	resp, err := client.NamedCredential.UpdateNamedCredential(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}
	d.Partial(false)

	return diags
}
