// Code generated by go-swagger; DO NOT EDIT.

package event_relay_feedback_lookup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"log"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new event relay feedback lookup API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for event relay feedback lookup API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetQuery gets event relay feedback lookup
*/
func (a *Client) GetQuery(params *GetQueryParams) (*GetQueryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetQueryParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getQuery",
		Method:             "GET",
		PathPattern:        "/query",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetQueryReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		log.Printf("[TRACE] err: %+v", err)
		return nil, err
	}
	return result.(*GetQueryOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
