// Code generated by go-swagger; DO NOT EDIT.

package platform_event_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// NewCreatePlatformEventChannelParams creates a new CreatePlatformEventChannelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePlatformEventChannelParams() *CreatePlatformEventChannelParams {
	return &CreatePlatformEventChannelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePlatformEventChannelParamsWithTimeout creates a new CreatePlatformEventChannelParams object
// with the ability to set a timeout on a request.
func NewCreatePlatformEventChannelParamsWithTimeout(timeout time.Duration) *CreatePlatformEventChannelParams {
	return &CreatePlatformEventChannelParams{
		timeout: timeout,
	}
}

// NewCreatePlatformEventChannelParamsWithContext creates a new CreatePlatformEventChannelParams object
// with the ability to set a context for a request.
func NewCreatePlatformEventChannelParamsWithContext(ctx context.Context) *CreatePlatformEventChannelParams {
	return &CreatePlatformEventChannelParams{
		Context: ctx,
	}
}

// NewCreatePlatformEventChannelParamsWithHTTPClient creates a new CreatePlatformEventChannelParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePlatformEventChannelParamsWithHTTPClient(client *http.Client) *CreatePlatformEventChannelParams {
	return &CreatePlatformEventChannelParams{
		HTTPClient: client,
	}
}

/*
CreatePlatformEventChannelParams contains all the parameters to send to the API endpoint

	for the create platform event channel operation.

	Typically these are written to a http.Request.
*/
type CreatePlatformEventChannelParams struct {

	// Body.
	Body *models.PlatformEventChannel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create platform event channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePlatformEventChannelParams) WithDefaults() *CreatePlatformEventChannelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create platform event channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePlatformEventChannelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create platform event channel params
func (o *CreatePlatformEventChannelParams) WithTimeout(timeout time.Duration) *CreatePlatformEventChannelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create platform event channel params
func (o *CreatePlatformEventChannelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create platform event channel params
func (o *CreatePlatformEventChannelParams) WithContext(ctx context.Context) *CreatePlatformEventChannelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create platform event channel params
func (o *CreatePlatformEventChannelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create platform event channel params
func (o *CreatePlatformEventChannelParams) WithHTTPClient(client *http.Client) *CreatePlatformEventChannelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create platform event channel params
func (o *CreatePlatformEventChannelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create platform event channel params
func (o *CreatePlatformEventChannelParams) WithBody(body *models.PlatformEventChannel) *CreatePlatformEventChannelParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create platform event channel params
func (o *CreatePlatformEventChannelParams) SetBody(body *models.PlatformEventChannel) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePlatformEventChannelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
