// Code generated by go-swagger; DO NOT EDIT.

package platform_event_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeletePlatformEventChannelParams creates a new DeletePlatformEventChannelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeletePlatformEventChannelParams() *DeletePlatformEventChannelParams {
	return &DeletePlatformEventChannelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePlatformEventChannelParamsWithTimeout creates a new DeletePlatformEventChannelParams object
// with the ability to set a timeout on a request.
func NewDeletePlatformEventChannelParamsWithTimeout(timeout time.Duration) *DeletePlatformEventChannelParams {
	return &DeletePlatformEventChannelParams{
		timeout: timeout,
	}
}

// NewDeletePlatformEventChannelParamsWithContext creates a new DeletePlatformEventChannelParams object
// with the ability to set a context for a request.
func NewDeletePlatformEventChannelParamsWithContext(ctx context.Context) *DeletePlatformEventChannelParams {
	return &DeletePlatformEventChannelParams{
		Context: ctx,
	}
}

// NewDeletePlatformEventChannelParamsWithHTTPClient creates a new DeletePlatformEventChannelParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeletePlatformEventChannelParamsWithHTTPClient(client *http.Client) *DeletePlatformEventChannelParams {
	return &DeletePlatformEventChannelParams{
		HTTPClient: client,
	}
}

/*
DeletePlatformEventChannelParams contains all the parameters to send to the API endpoint

	for the delete platform event channel operation.

	Typically these are written to a http.Request.
*/
type DeletePlatformEventChannelParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete platform event channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePlatformEventChannelParams) WithDefaults() *DeletePlatformEventChannelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete platform event channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePlatformEventChannelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete platform event channel params
func (o *DeletePlatformEventChannelParams) WithTimeout(timeout time.Duration) *DeletePlatformEventChannelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete platform event channel params
func (o *DeletePlatformEventChannelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete platform event channel params
func (o *DeletePlatformEventChannelParams) WithContext(ctx context.Context) *DeletePlatformEventChannelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete platform event channel params
func (o *DeletePlatformEventChannelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete platform event channel params
func (o *DeletePlatformEventChannelParams) WithHTTPClient(client *http.Client) *DeletePlatformEventChannelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete platform event channel params
func (o *DeletePlatformEventChannelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete platform event channel params
func (o *DeletePlatformEventChannelParams) WithID(id string) *DeletePlatformEventChannelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete platform event channel params
func (o *DeletePlatformEventChannelParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePlatformEventChannelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
