// Code generated by go-swagger; DO NOT EDIT.

package platform_event_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// DeletePlatformEventChannelReader is a Reader for the DeletePlatformEventChannel structure.
type DeletePlatformEventChannelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePlatformEventChannelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePlatformEventChannelNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeletePlatformEventChannelDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePlatformEventChannelNoContent creates a DeletePlatformEventChannelNoContent with default headers values
func NewDeletePlatformEventChannelNoContent() *DeletePlatformEventChannelNoContent {
	return &DeletePlatformEventChannelNoContent{}
}

/*
DeletePlatformEventChannelNoContent describes a response with status code 204, with default header values.

successful operation
*/
type DeletePlatformEventChannelNoContent struct {
}

func (o *DeletePlatformEventChannelNoContent) Error() string {
	return fmt.Sprintf("[DELETE /PlatformEventChannel/{Id}][%d] deletePlatformEventChannelNoContent ", 204)
}

func (o *DeletePlatformEventChannelNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	//  bytes, _ := io.ReadAll(response.Body())
	//  log.Printf("[TRACE] response body: ", string(bytes))
	//  log.Printf("[TRACE] response code: ", response.Code())

	return nil
}

// NewDeletePlatformEventChannelDefault creates a DeletePlatformEventChannelDefault with default headers values
func NewDeletePlatformEventChannelDefault(code int) *DeletePlatformEventChannelDefault {
	return &DeletePlatformEventChannelDefault{
		_statusCode: code,
	}
}

/*
DeletePlatformEventChannelDefault describes a response with status code -1, with default header values.

Error
*/
type DeletePlatformEventChannelDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the delete platform event channel default response
func (o *DeletePlatformEventChannelDefault) Code() int {
	return o._statusCode
}

func (o *DeletePlatformEventChannelDefault) Error() string {
	return fmt.Sprintf("[DELETE /PlatformEventChannel/{Id}][%d] deletePlatformEventChannel default  %+v", o._statusCode, o.Payload)
}
func (o *DeletePlatformEventChannelDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeletePlatformEventChannelDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	//  bytes, _ := io.ReadAll(response.Body())
	//  log.Printf("[TRACE] response body: ", string(bytes))
	//  log.Printf("[TRACE] response code: ", response.Code())

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
