// Code generated by go-swagger; DO NOT EDIT.

package platform_event_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// GetPlatformEventChannelReader is a Reader for the GetPlatformEventChannel structure.
type GetPlatformEventChannelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlatformEventChannelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlatformEventChannelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetPlatformEventChannelDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPlatformEventChannelOK creates a GetPlatformEventChannelOK with default headers values
func NewGetPlatformEventChannelOK() *GetPlatformEventChannelOK {
	return &GetPlatformEventChannelOK{}
}

/*
GetPlatformEventChannelOK describes a response with status code 200, with default header values.

successful operation
*/
type GetPlatformEventChannelOK struct {
	Payload *models.PlatformEventChannel
}

func (o *GetPlatformEventChannelOK) Error() string {
	s := fmt.Sprintf("%+v", o.Payload)
	b, err := json.Marshal(o.Payload)
	if err == nil {
		s = string(b)
	}
	return fmt.Sprintf("[GET /tooling/sobjects/PlatformEventChannel/{Id}][%d] getPlatformEventChannelOK  %s", 200, s)
}
func (o *GetPlatformEventChannelOK) GetPayload() *models.PlatformEventChannel {
	return o.Payload
}

func (o *GetPlatformEventChannelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PlatformEventChannel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlatformEventChannelDefault creates a GetPlatformEventChannelDefault with default headers values
func NewGetPlatformEventChannelDefault(code int) *GetPlatformEventChannelDefault {
	return &GetPlatformEventChannelDefault{
		_statusCode: code,
	}
}

/*
GetPlatformEventChannelDefault describes a response with status code -1, with default header values.

Error
*/
type GetPlatformEventChannelDefault struct {
	_statusCode int

	Payload []*models.ErrorResponse
}

// Code gets the status code for the get platform event channel default response
func (o *GetPlatformEventChannelDefault) Code() int {
	return o._statusCode
}

func (o *GetPlatformEventChannelDefault) Error() string {
	s := fmt.Sprintf("%+v", o.Payload)
	b, err := json.Marshal(o.Payload)
	if err == nil {
		s = string(b)
	}
	return fmt.Sprintf("[GET /tooling/sobjects/PlatformEventChannel/{Id}][%d] getPlatformEventChannel default  %s", o._statusCode, s)
}
func (o *GetPlatformEventChannelDefault) GetPayload() []*models.ErrorResponse {
	return o.Payload
}

func (o *GetPlatformEventChannelDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
