// Code generated by go-swagger; DO NOT EDIT.

package platform_event_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPlatformEventChannelParams creates a new GetPlatformEventChannelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPlatformEventChannelParams() *GetPlatformEventChannelParams {
	return &GetPlatformEventChannelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPlatformEventChannelParamsWithTimeout creates a new GetPlatformEventChannelParams object
// with the ability to set a timeout on a request.
func NewGetPlatformEventChannelParamsWithTimeout(timeout time.Duration) *GetPlatformEventChannelParams {
	return &GetPlatformEventChannelParams{
		timeout: timeout,
	}
}

// NewGetPlatformEventChannelParamsWithContext creates a new GetPlatformEventChannelParams object
// with the ability to set a context for a request.
func NewGetPlatformEventChannelParamsWithContext(ctx context.Context) *GetPlatformEventChannelParams {
	return &GetPlatformEventChannelParams{
		Context: ctx,
	}
}

// NewGetPlatformEventChannelParamsWithHTTPClient creates a new GetPlatformEventChannelParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPlatformEventChannelParamsWithHTTPClient(client *http.Client) *GetPlatformEventChannelParams {
	return &GetPlatformEventChannelParams{
		HTTPClient: client,
	}
}

/*
GetPlatformEventChannelParams contains all the parameters to send to the API endpoint

	for the get platform event channel operation.

	Typically these are written to a http.Request.
*/
type GetPlatformEventChannelParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get platform event channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlatformEventChannelParams) WithDefaults() *GetPlatformEventChannelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get platform event channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlatformEventChannelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get platform event channel params
func (o *GetPlatformEventChannelParams) WithTimeout(timeout time.Duration) *GetPlatformEventChannelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get platform event channel params
func (o *GetPlatformEventChannelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get platform event channel params
func (o *GetPlatformEventChannelParams) WithContext(ctx context.Context) *GetPlatformEventChannelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get platform event channel params
func (o *GetPlatformEventChannelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get platform event channel params
func (o *GetPlatformEventChannelParams) WithHTTPClient(client *http.Client) *GetPlatformEventChannelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get platform event channel params
func (o *GetPlatformEventChannelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get platform event channel params
func (o *GetPlatformEventChannelParams) WithID(id string) *GetPlatformEventChannelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get platform event channel params
func (o *GetPlatformEventChannelParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPlatformEventChannelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
