// Code generated by go-swagger; DO NOT EDIT.

package platform_event_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"vestahealthcare/models"
)

// NewUpdatePlatformEventChannelParams creates a new UpdatePlatformEventChannelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePlatformEventChannelParams() *UpdatePlatformEventChannelParams {
	return &UpdatePlatformEventChannelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePlatformEventChannelParamsWithTimeout creates a new UpdatePlatformEventChannelParams object
// with the ability to set a timeout on a request.
func NewUpdatePlatformEventChannelParamsWithTimeout(timeout time.Duration) *UpdatePlatformEventChannelParams {
	return &UpdatePlatformEventChannelParams{
		timeout: timeout,
	}
}

// NewUpdatePlatformEventChannelParamsWithContext creates a new UpdatePlatformEventChannelParams object
// with the ability to set a context for a request.
func NewUpdatePlatformEventChannelParamsWithContext(ctx context.Context) *UpdatePlatformEventChannelParams {
	return &UpdatePlatformEventChannelParams{
		Context: ctx,
	}
}

// NewUpdatePlatformEventChannelParamsWithHTTPClient creates a new UpdatePlatformEventChannelParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePlatformEventChannelParamsWithHTTPClient(client *http.Client) *UpdatePlatformEventChannelParams {
	return &UpdatePlatformEventChannelParams{
		HTTPClient: client,
	}
}

/*
UpdatePlatformEventChannelParams contains all the parameters to send to the API endpoint

	for the update platform event channel operation.

	Typically these are written to a http.Request.
*/
type UpdatePlatformEventChannelParams struct {

	// ID.
	ID string

	// Body.
	Body *models.PlatformEventChannelUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update platform event channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePlatformEventChannelParams) WithDefaults() *UpdatePlatformEventChannelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update platform event channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePlatformEventChannelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) WithTimeout(timeout time.Duration) *UpdatePlatformEventChannelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) WithContext(ctx context.Context) *UpdatePlatformEventChannelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) WithHTTPClient(client *http.Client) *UpdatePlatformEventChannelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) WithID(id string) *UpdatePlatformEventChannelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) SetID(id string) {
	o.ID = id
}

// WithBody adds the body to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) WithBody(body *models.PlatformEventChannelUpdateRequest) *UpdatePlatformEventChannelParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update platform event channel params
func (o *UpdatePlatformEventChannelParams) SetBody(body *models.PlatformEventChannelUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePlatformEventChannelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Id
	if err := r.SetPathParam("Id", o.ID); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
