name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      # - name: fmt
      #   run: make fmt-check
      - name: Generate provider
        run: make generate
      - name: Run tests
        run: make test
      - name: Publish
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: build --snapshot --rm-dist
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: providers
          path: dist/*
