// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NamedCredentialCreateResponse named credential create response
// Example: isResource
//
// swagger:model NamedCredentialCreateResponse
type NamedCredentialCreateResponse struct {

	// id
	// Example: 1234
	ID string `json:"id,omitempty"`
}

// Validate validates this named credential create response
func (m *NamedCredentialCreateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this named credential create response based on context it is used
func (m *NamedCredentialCreateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NamedCredentialCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NamedCredentialCreateResponse) UnmarshalBinary(b []byte) error {
	var res NamedCredentialCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
