// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlatformEventChannelMemberMetadata platform event channel member metadata
//
// swagger:model PlatformEventChannelMemberMetadata
type PlatformEventChannelMemberMetadata struct {

	// event channel
	// Example: My_Channel__chn
	// Required: true
	EventChannel *string `json:"eventChannel"`

	// selected entity
	// Example: AccountChangeEvent
	// Required: true
	SelectedEntity *string `json:"selectedEntity"`
}

// Validate validates this platform event channel member metadata
func (m *PlatformEventChannelMemberMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventChannel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSelectedEntity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlatformEventChannelMemberMetadata) validateEventChannel(formats strfmt.Registry) error {

	if err := validate.Required("eventChannel", "body", m.EventChannel); err != nil {
		return err
	}

	return nil
}

func (m *PlatformEventChannelMemberMetadata) validateSelectedEntity(formats strfmt.Registry) error {

	if err := validate.Required("selectedEntity", "body", m.SelectedEntity); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this platform event channel member metadata based on context it is used
func (m *PlatformEventChannelMemberMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlatformEventChannelMemberMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlatformEventChannelMemberMetadata) UnmarshalBinary(b []byte) error {
	var res PlatformEventChannelMemberMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
