// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlatformEventChannelCreateResponse platform event channel create response
// Example: isResource
//
// swagger:model PlatformEventChannelCreateResponse
type PlatformEventChannelCreateResponse struct {

	// id
	// Example: 1234
	ID string `json:"id,omitempty"`
}

// Validate validates this platform event channel create response
func (m *PlatformEventChannelCreateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this platform event channel create response based on context it is used
func (m *PlatformEventChannelCreateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlatformEventChannelCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlatformEventChannelCreateResponse) UnmarshalBinary(b []byte) error {
	var res PlatformEventChannelCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
