// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlatformEventChannelMemberCreateResponse platform event channel member create response
// Example: isResource
//
// swagger:model PlatformEventChannelMemberCreateResponse
type PlatformEventChannelMemberCreateResponse struct {

	// Id
	// Example: 1234
	ID string `json:"Id,omitempty"`
}

// Validate validates this platform event channel member create response
func (m *PlatformEventChannelMemberCreateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this platform event channel member create response based on context it is used
func (m *PlatformEventChannelMemberCreateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlatformEventChannelMemberCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlatformEventChannelMemberCreateResponse) UnmarshalBinary(b []byte) error {
	var res PlatformEventChannelMemberCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
